name: techs_html_bindings
description: Very opinionated HTML bindings, for personal use in generating websites.
version: 1.0.0
repository: https://github.com/TechnicJelle/techs_html_bindings

environment:
  sdk: ^3.8.1

dependencies:
  image: ^4.6.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.28.0
  very_good_analysis: ^10.0.0
